// GENERATED by tools/gen-levels.mjs -- do not edit by hand.
// campaign: 5 chapters x 8 stages, deterministic per level id.
// puzzle: 24 fixed boards, every one verified solvable by the chain solver.
export const CHAPTERS = [
  { id: 1, nameKey: "chapter_1", from: 1, to: 8 },
  { id: 2, nameKey: "chapter_2", from: 9, to: 16 },
  { id: 3, nameKey: "chapter_3", from: 17, to: 24 },
  { id: 4, nameKey: "chapter_4", from: 25, to: 32 },
  { id: 5, nameKey: "chapter_5", from: 33, to: 40 },
];

export const CAMPAIGN_LEVELS = [
 {
  "id": "level_1_1",
  "mode": "campaign",
  "chapter": 1,
  "index": 1,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o....oo.#",
   "#.#.#o#.#.#.#",
   "#.......ooo.#",
   "#.#.#.#.#.#.#",
   "#.o.oo.....o#",
   "#.#.#.#.#.#.#",
   "#.....o.....#",
   "#.#o#.#o#.#o#",
   "#..o........#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 6,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 7,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 9,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 3,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3750252221
 },
 {
  "id": "level_1_2",
  "mode": "campaign",
  "chapter": 1,
  "index": 2,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#......o....#",
   "#.#.#o#.#.#.#",
   "#..........o#",
   "#.#.#.#.#o#o#",
   "#........o..#",
   "#.#.#.#.#.#.#",
   "#o.o.o....o.#",
   "#.#.#.#.#.#.#",
   "#....o.o.o..#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 1,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 7,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 9,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3699919364
 },
 {
  "id": "level_1_3",
  "mode": "campaign",
  "chapter": 1,
  "index": 3,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.......#",
   "#.#o#.#o#.#.#",
   "#..oo.o.....#",
   "#.#.#.#.#.#.#",
   "#.o.o.....oo#",
   "#o#.#.#.#o#.#",
   "#o....o.....#",
   "#.#.#.#.#.#.#",
   "#o....o.o...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 10,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "balloon"
   },
   {
    "cx": 5,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 5,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 8,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3716696983
 },
 {
  "id": "level_1_4",
  "mode": "campaign",
  "chapter": 1,
  "index": 4,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....o..o..o#",
   "#.#o#.#.#o#.#",
   "#...o.......#",
   "#.#.#o#.#o#.#",
   "#.......o...#",
   "#.#o#.#.#.#.#",
   "#........o..#",
   "#o#.#.#.#.#.#",
   "#o...o...o.o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 6,
    "type": "balloon"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 10,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 3,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 7,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3666364126
 },
 {
  "id": "level_1_5",
  "mode": "campaign",
  "chapter": 1,
  "index": 5,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.......oo.o#",
   "#.#.#.#o#.#.#",
   "#.o.....o...#",
   "#.#o#.#.#.#.#",
   "#o.o...o..o.#",
   "#.#.#.#o#o#.#",
   "#.......o.o.#",
   "#.#.#.#.#.#o#",
   "#..o..o...o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 8,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 2,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3683141745
 },
 {
  "id": "level_1_6",
  "mode": "campaign",
  "chapter": 1,
  "index": 6,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....oo....#",
   "#.#.#.#.#.#o#",
   "#..o....o...#",
   "#.#o#o#.#o#.#",
   "#o...o....o.#",
   "#.#.#o#.#o#.#",
   "#.....o....o#",
   "#.#.#.#.#.#.#",
   "#.oo...o....#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 2,
    "type": "balloon"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 2,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 7,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 7,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3632808888
 },
 {
  "id": "level_1_7",
  "mode": "campaign",
  "chapter": 1,
  "index": 7,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o..o....#",
   "#.#.#o#.#o#.#",
   "#........o..#",
   "#.#.#.#.#o#.#",
   "#oo..o....oo#",
   "#.#.#o#.#.#.#",
   "#.....o....o#",
   "#.#o#.#.#.#o#",
   "#..o...oo...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 1,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 5,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 7,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 1,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 5,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3649586507
 },
 {
  "id": "level_1_8",
  "mode": "campaign",
  "chapter": 1,
  "index": 8,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.......#",
   "#.#o#.#o#.#o#",
   "#....o....o.#",
   "#.#.#.#o#o#o#",
   "#.o.o...o...#",
   "#.#.#.#.#.#.#",
   "#o.oo.o....o#",
   "#.#.#.#.#.#o#",
   "#...o.......#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 10,
    "cy": 1,
    "type": "balloon"
   },
   {
    "cx": 11,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 6,
    "cy": 1,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 2,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 182,
  "fire": 1,
  "bombs": 1,
  "seed": 3599253650
 },
 {
  "id": "level_2_1",
  "mode": "campaign",
  "chapter": 2,
  "index": 1,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....o......#",
   "#.#.#.#.#o#.#",
   "#....oo....o#",
   "#o#o#o#.#.#.#",
   "#o......oo..#",
   "#.#.#.#.#.#.#",
   "#...........#",
   "#o#.#o#o#.#.#",
   "#......oo.o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 5,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "chaser"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "chaser"
   },
   {
    "cx": 11,
    "cy": 8,
    "type": "chaser"
   },
   {
    "cx": 6,
    "cy": 7,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 8,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 192170872
 },
 {
  "id": "level_2_2",
  "mode": "campaign",
  "chapter": 2,
  "index": 2,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.......#",
   "#.#o#o#.#.#.#",
   "#..o...o.o..#",
   "#.#.#o#o#.#o#",
   "#o..........#",
   "#.#o#.#.#.#.#",
   "#.....o...o.#",
   "#.#.#o#.#.#o#",
   "#o...o.o..o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 1,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 4,
    "cy": 3,
    "type": "balloon"
   },
   {
    "cx": 6,
    "cy": 9,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 2,
    "type": "chaser"
   },
   {
    "cx": 2,
    "cy": 7,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 242503729
 },
 {
  "id": "level_2_3",
  "mode": "campaign",
  "chapter": 2,
  "index": 3,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#..........o#",
   "#.#.#o#.#o#.#",
   "#....o......#",
   "#.#o#.#.#.#o#",
   "#.....o....o#",
   "#.#.#.#o#.#.#",
   "#..o....oo..#",
   "#.#.#.#o#o#.#",
   "#..o......oo#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 5,
    "cy": 4,
    "type": "balloon"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 8,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "remote",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 225726110
 },
 {
  "id": "level_2_4",
  "mode": "campaign",
  "chapter": 2,
  "index": 4,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....o.....o#",
   "#.#.#.#.#.#.#",
   "#..oo......o#",
   "#o#.#.#.#o#o#",
   "#o......o...#",
   "#.#.#o#.#o#.#",
   "#....oo...o.#",
   "#.#.#.#o#.#.#",
   "#.......o..o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 2,
    "type": "balloon"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "chaser"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "balloon"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 276058967
 },
 {
  "id": "level_2_5",
  "mode": "campaign",
  "chapter": 2,
  "index": 5,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.o.....#",
   "#.#o#o#.#o#.#",
   "#.o.....o...#",
   "#.#.#.#.#o#o#",
   "#..o...o.o..#",
   "#o#.#o#.#.#.#",
   "#......oo...#",
   "#o#.#.#o#.#o#",
   "#.........o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 8,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 7,
    "type": "balloon"
   },
   {
    "cx": 6,
    "cy": 5,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 259281348
 },
 {
  "id": "level_2_6",
  "mode": "campaign",
  "chapter": 2,
  "index": 6,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....oo.oo.#",
   "#.#.#.#.#.#.#",
   "#.o..oo.....#",
   "#o#o#.#.#.#o#",
   "#o..........#",
   "#.#.#.#.#.#.#",
   "#.o.o.o....o#",
   "#o#.#.#.#.#.#",
   "#..........o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 5,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 3,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 4,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 1,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 309614205
 },
 {
  "id": "level_2_7",
  "mode": "campaign",
  "chapter": 2,
  "index": 7,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.....o.#",
   "#.#.#o#o#.#.#",
   "#.ooo...o...#",
   "#.#.#.#o#.#.#",
   "#...oo...o.o#",
   "#o#.#.#.#.#.#",
   "#o...o.o...o#",
   "#.#o#.#.#.#.#",
   "#o......o...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 8,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "balloon"
   },
   {
    "cx": 6,
    "cy": 7,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 8,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 7,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 292836586
 },
 {
  "id": "level_2_8",
  "mode": "campaign",
  "chapter": 2,
  "index": 8,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....o...o.#",
   "#.#o#.#o#o#.#",
   "#...o......o#",
   "#.#.#.#.#.#o#",
   "#..o.o..o...#",
   "#.#.#.#.#o#.#",
   "#o........o.#",
   "#.#.#o#o#.#.#",
   "#.o.o...o.oo#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 1,
    "type": "chaser"
   },
   {
    "cx": 5,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 6,
    "type": "chaser"
   },
   {
    "cx": 2,
    "cy": 7,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 9,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 194,
  "fire": 1,
  "bombs": 1,
  "seed": 74727539
 },
 {
  "id": "level_3_1",
  "mode": "campaign",
  "chapter": 3,
  "index": 1,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o...o...#",
   "#.#.#.#.#.#o#",
   "#.=...oo...o#",
   "#=#o#o#.#.#.#",
   "#.o.ooo.o.oo#",
   "#o#.#.#.#.#.#",
   "#...........#",
   "#.#o#.#.#o#.#",
   "#o...=......#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 6,
    "cy": 1,
    "type": "ghost"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "evader"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "ghost"
   },
   {
    "cx": 11,
    "cy": 4,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 5,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 2,
    "kind": "bomb",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 9,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 3923263571
 },
 {
  "id": "level_3_2",
  "mode": "campaign",
  "chapter": 3,
  "index": 2,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.......o...#",
   "#.#.#o#.#.#o#",
   "#..o......oo#",
   "#o#o#.#.#.#.#",
   "#...=..o..o.#",
   "#.#o#.#.#.#.#",
   "#.o=...o.o..#",
   "#.#.#.#.#.#.#",
   "#...o.....o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 9,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 5,
    "cy": 4,
    "type": "chaser"
   },
   {
    "cx": 2,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "evader"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 3940041190
 },
 {
  "id": "level_3_3",
  "mode": "campaign",
  "chapter": 3,
  "index": 3,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#..........o#",
   "#.#.#.#.#.#.#",
   "#.=......o..#",
   "#.#o#.#.#.#.#",
   "#.o.=.oo.o.o#",
   "#.#.#.#.#.#.#",
   "#.o..o.o....#",
   "#.#.#.#.#.#.#",
   "#......o..oo#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 8,
    "cy": 3,
    "type": "evader"
   },
   {
    "cx": 8,
    "cy": 1,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "ghost"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "ghost"
   },
   {
    "cx": 11,
    "cy": 4,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 5,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 3956818809
 },
 {
  "id": "level_3_4",
  "mode": "campaign",
  "chapter": 3,
  "index": 4,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#..........o#",
   "#.#=#.#.#.#o#",
   "#..o.....oo.#",
   "#o#o#o#=#.#.#",
   "#...oo.o....#",
   "#.#.#.#.#.#.#",
   "#.........o.#",
   "#.#.#.#o#.#.#",
   "#.o..=.o...o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 6,
    "cy": 5,
    "type": "chaser"
   },
   {
    "cx": 8,
    "cy": 1,
    "type": "balloon"
   },
   {
    "cx": 10,
    "cy": 1,
    "type": "ghost"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 3973596428
 },
 {
  "id": "level_3_5",
  "mode": "campaign",
  "chapter": 3,
  "index": 5,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o.o.o...#",
   "#.#.#o#.#o#o#",
   "#.o.........#",
   "#.#o#.#.#.#.#",
   "#...o.......#",
   "#.#.#.#.#.#.#",
   "#.....o.o.oo#",
   "#.#.#.#.#.#.#",
   "#.oo.oo.=.o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 4,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 1,
    "type": "chaser"
   },
   {
    "cx": 10,
    "cy": 3,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "evader"
   },
   {
    "cx": 2,
    "cy": 5,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 3990374047
 },
 {
  "id": "level_3_6",
  "mode": "campaign",
  "chapter": 3,
  "index": 6,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....o.o..o#",
   "#.#.#.#.#.#.#",
   "#.........o.#",
   "#.#o#=#.#.#.#",
   "#o.o...oo.o.#",
   "#.#o#.#.#.#.#",
   "#......o.o..#",
   "#.#o#.#.#.#.#",
   "#o......o.o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 10,
    "cy": 7,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 4,
    "cy": 5,
    "type": "evader"
   },
   {
    "cx": 11,
    "cy": 2,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 8,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 7,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 4007151666
 },
 {
  "id": "level_3_7",
  "mode": "campaign",
  "chapter": 3,
  "index": 7,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.......o.o.#",
   "#.#.#=#.#.#.#",
   "#......o..o.#",
   "#.#o#o#.#.#o#",
   "#......o..oo#",
   "#o#.#o#.#.#.#",
   "#...........#",
   "#.#=#.#=#.#.#",
   "#.o=.....o.o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 9,
    "cy": 4,
    "type": "evader"
   },
   {
    "cx": 4,
    "cy": 3,
    "type": "evader"
   },
   {
    "cx": 11,
    "cy": 8,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 1,
    "cy": 7,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 9,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 4023929285
 },
 {
  "id": "level_3_8",
  "mode": "campaign",
  "chapter": 3,
  "index": 8,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....=...o..#",
   "#.#.#o#.#.#.#",
   "#.o=o......o#",
   "#.#.#.#o#.#o#",
   "#...o..o....#",
   "#o#.#.#o#.#.#",
   "#.o.....o...#",
   "#.#.#.#.#o#.#",
   "#..o...o..o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 10,
    "cy": 7,
    "type": "ghost"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "ghost"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 8,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 206,
  "fire": 1,
  "bombs": 1,
  "seed": 4040706904
 },
 {
  "id": "level_4_1",
  "mode": "campaign",
  "chapter": 4,
  "index": 1,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....o....=#",
   "#.#o#.#.#=#.#",
   "#.o........o#",
   "#o#o#.#o#.#.#",
   "#o.o..o...o.#",
   "#.#.#.#o#o#.#",
   "#.....o...o.#",
   "#.#.#.#.#=#.#",
   "#....=..o...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 9,
    "cy": 9,
    "type": "balloon"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 7,
    "cy": 5,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 7,
    "type": "ghost"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 8,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 7,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 902066030
 },
 {
  "id": "level_4_2",
  "mode": "campaign",
  "chapter": 4,
  "index": 2,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....=.o....#",
   "#.#.#o#.#.#.#",
   "#.o=........#",
   "#o#.#.#.#.#.#",
   "#o......o...#",
   "#.#.#o#.#.#.#",
   "#o....=....o#",
   "#.#.#o#.#.#.#",
   "#...o.o....o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 9,
    "cy": 8,
    "type": "armored"
   },
   {
    "cx": 11,
    "cy": 4,
    "type": "chaser"
   },
   {
    "cx": 10,
    "cy": 1,
    "type": "ghost"
   },
   {
    "cx": 8,
    "cy": 9,
    "type": "evader"
   },
   {
    "cx": 11,
    "cy": 2,
    "type": "ghost"
   },
   {
    "cx": 10,
    "cy": 5,
    "type": "evader"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 5,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 8,
    "kind": "kick",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 885288411
 },
 {
  "id": "level_4_3",
  "mode": "campaign",
  "chapter": 4,
  "index": 3,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o...o=..#",
   "#.#.#.#=#.#.#",
   "#...........#",
   "#.#.#.#o#.#.#",
   "#.o.ooo.....#",
   "#o#.#o#.#.#o#",
   "#.o...o...o.#",
   "#.#.#o#o#.#o#",
   "#.=.o.=.....#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 8,
    "cy": 3,
    "type": "evader"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "ghost"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 9,
    "type": "ghost"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "armored"
   },
   {
    "cx": 5,
    "cy": 4,
    "type": "evader"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 6,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 8,
    "kind": "kick",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 868510792
 },
 {
  "id": "level_4_4",
  "mode": "campaign",
  "chapter": 4,
  "index": 4,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o..o...o#",
   "#.#.#.#o#.#.#",
   "#..o..o....o#",
   "#.#.#.#o#o#.#",
   "#......o....#",
   "#.#.#.#.#.#.#",
   "#..o......o.#",
   "#.#.#.#o#.#.#",
   "#=.o......oo#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 1,
    "cy": 6,
    "type": "ghost"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "chaser"
   },
   {
    "cx": 8,
    "cy": 9,
    "type": "chaser"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "armored"
   },
   {
    "cx": 3,
    "cy": 4,
    "type": "balloon"
   },
   {
    "cx": 11,
    "cy": 2,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 4,
    "kind": "curse",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 985954125
 },
 {
  "id": "level_4_5",
  "mode": "campaign",
  "chapter": 4,
  "index": 5,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#..........=#",
   "#.#.#.#=#.#.#",
   "#.=o...o=.o=#",
   "#=#o#.#.#.#.#",
   "#...o..o....#",
   "#.#.#.#.#.#.#",
   "#......o.o.o#",
   "#.#.#.#.#.#.#",
   "#=o.oo.....=#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 3,
    "type": "chaser"
   },
   {
    "cx": 11,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "ghost"
   },
   {
    "cx": 7,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 3,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 5,
    "cy": 8,
    "type": "evader"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 3,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 969176506
 },
 {
  "id": "level_4_6",
  "mode": "campaign",
  "chapter": 4,
  "index": 6,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....o...=..#",
   "#.#o#.#o#.#o#",
   "#...o...oo..#",
   "#o#o#.#=#.#.#",
   "#.=o........#",
   "#.#.#.#.#.#.#",
   "#.o.o.o.=...#",
   "#.#.#.#.#=#.#",
   "#..=.....oo.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 8,
    "cy": 9,
    "type": "ghost"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "chaser"
   },
   {
    "cx": 8,
    "cy": 5,
    "type": "armored"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "balloon"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "armored"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "armored"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 8,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 2,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 952398887
 },
 {
  "id": "level_4_7",
  "mode": "campaign",
  "chapter": 4,
  "index": 7,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...oo......#",
   "#.#.#=#o#o#.#",
   "#..oo....o..#",
   "#.#.#.#o#.#.#",
   "#...=.o..=..#",
   "#.#.#.#.#.#.#",
   "#.oo..oo....#",
   "#.#.#o#=#.#.#",
   "#=.o....=.==#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 10,
    "cy": 7,
    "type": "ghost"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "ghost"
   },
   {
    "cx": 1,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 9,
    "cy": 8,
    "type": "balloon"
   },
   {
    "cx": 7,
    "cy": 5,
    "type": "ghost"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "armored"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 7,
    "kind": "kick",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 935621268
 },
 {
  "id": "level_4_8",
  "mode": "campaign",
  "chapter": 4,
  "index": 8,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....o....o#",
   "#.#.#o#.#.#o#",
   "#.o..o.o....#",
   "#.#.#.#o#.#.#",
   "#.o.....o...#",
   "#.#.#.#=#o#o#",
   "#.o....==...#",
   "#.#.#.#.#.#o#",
   "#.o=.o=....=#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 6,
    "cy": 7,
    "type": "evader"
   },
   {
    "cx": 3,
    "cy": 4,
    "type": "ghost"
   },
   {
    "cx": 4,
    "cy": 7,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 5,
    "type": "armored"
   },
   {
    "cx": 5,
    "cy": 4,
    "type": "evader"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 8,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 6,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "pierce",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 218,
  "fire": 1,
  "bombs": 1,
  "seed": 784622697
 },
 {
  "id": "level_5_1",
  "mode": "campaign",
  "chapter": 5,
  "index": 1,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...o=..o...#",
   "#.#.#.#=#o#=#",
   "#...=.o..o..#",
   "#.#.#.#.#.#.#",
   "#...o.......#",
   "#.#.#.#.#.#.#",
   "#oo.=o......#",
   "#.#o#.#.#o#.#",
   "#....o.=o...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 10,
    "cy": 5,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 6,
    "type": "evader"
   },
   {
    "cx": 9,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "armored"
   },
   {
    "cx": 11,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 9,
    "cy": 1,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 8,
    "cy": 9,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 2,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 3,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 7,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 9,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2464938313
 },
 {
  "id": "level_5_2",
  "mode": "campaign",
  "chapter": 5,
  "index": 2,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....o.....#",
   "#.#.#.#.#o#.#",
   "#.=.o.o....o#",
   "#.#.#.#o#=#.#",
   "#......=....#",
   "#.#o#.#=#.#.#",
   "#o.o......o.#",
   "#.#.#o#.#.#.#",
   "#.o...o..oo.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 1,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 1,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 6,
    "cy": 7,
    "type": "armored"
   },
   {
    "cx": 7,
    "cy": 3,
    "type": "evader"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 8,
    "cy": 9,
    "type": "balloon"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 4,
    "kind": "shield",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 10,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2414605456
 },
 {
  "id": "level_5_3",
  "mode": "campaign",
  "chapter": 5,
  "index": 3,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....o...o..#",
   "#.#.#o#.#.#o#",
   "#.o.=....=o.#",
   "#=#o#.#.#.#.#",
   "#......=..=.#",
   "#o#.#o#.#.#.#",
   "#o...o....o.#",
   "#.#.#.#o#.#=#",
   "#....=.o....#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 3,
    "type": "ghost"
   },
   {
    "cx": 2,
    "cy": 5,
    "type": "ghost"
   },
   {
    "cx": 6,
    "cy": 9,
    "type": "armored"
   },
   {
    "cx": 5,
    "cy": 8,
    "type": "ghost"
   },
   {
    "cx": 7,
    "cy": 2,
    "type": "balloon"
   },
   {
    "cx": 4,
    "cy": 7,
    "type": "armored"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 7,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 2,
    "kind": "speed",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2431383075
 },
 {
  "id": "level_5_4",
  "mode": "campaign",
  "chapter": 5,
  "index": 4,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#...oo....oo#",
   "#.#o#o#.#.#.#",
   "#.==o.o.....#",
   "#.#.#.#.#.#.#",
   "#......o....#",
   "#.#.#.#.#.#.#",
   "#.o....o.o..#",
   "#.#o#=#.#.#o#",
   "#oo.......o.#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 11,
    "cy": 2,
    "type": "armored"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "chaser"
   },
   {
    "cx": 8,
    "cy": 5,
    "type": "armored"
   },
   {
    "cx": 4,
    "cy": 7,
    "type": "evader"
   },
   {
    "cx": 3,
    "cy": 9,
    "type": "armored"
   }
  ],
  "powerups": [
   {
    "cx": 10,
    "cy": 9,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 7,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 5,
    "cy": 8,
    "kind": "fire",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 1,
    "kind": "fire",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 8,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2515271170
 },
 {
  "id": "level_5_5",
  "mode": "campaign",
  "chapter": 5,
  "index": 5,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#.....=.....#",
   "#.#=#.#=#.#.#",
   "#.==...=...=#",
   "#o#.#.#.#.#o#",
   "#.o....o=.o.#",
   "#.#.#.#.#.#.#",
   "#.o=....o...#",
   "#.#.#.#=#.#.#",
   "#=.....o=...#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 1,
    "type": "chaser"
   },
   {
    "cx": 4,
    "cy": 9,
    "type": "ghost"
   },
   {
    "cx": 8,
    "cy": 3,
    "type": "chaser"
   },
   {
    "cx": 9,
    "cy": 1,
    "type": "evader"
   },
   {
    "cx": 6,
    "cy": 7,
    "type": "chaser"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "ghost"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "ghost"
   }
  ],
  "powerups": [
   {
    "cx": 7,
    "cy": 9,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 5,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "bomb",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 8,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 3,
    "kind": "curse",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 8,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2532048789
 },
 {
  "id": "level_5_6",
  "mode": "campaign",
  "chapter": 5,
  "index": 6,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#........==.#",
   "#.#o#.#.#.#.#",
   "#..o...==.=.#",
   "#.#.#.#o#.#=#",
   "#.=.....=...#",
   "#o#.#.#=#.#.#",
   "#o....o.....#",
   "#.#o#.#.#.#o#",
   "#.....=....=#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 9,
    "cy": 6,
    "type": "armored"
   },
   {
    "cx": 7,
    "cy": 7,
    "type": "evader"
   },
   {
    "cx": 11,
    "cy": 6,
    "type": "ghost"
   },
   {
    "cx": 11,
    "cy": 3,
    "type": "chaser"
   },
   {
    "cx": 6,
    "cy": 1,
    "type": "chaser"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 11,
    "cy": 8,
    "kind": "speed",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 6,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 3,
    "kind": "kick",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 5,
    "kind": "shield",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2481715932
 },
 {
  "id": "level_5_7",
  "mode": "campaign",
  "chapter": 5,
  "index": 7,
  "cols": 13,
  "rows": 11,
  "tiles": [
   "#############",
   "#....==.....#",
   "#.#.#.#.#.#=#",
   "#..o.....o..#",
   "#o#.#.#.#.#o#",
   "#.o......o..#",
   "#.#.#.#.#o#.#",
   "#......oo...#",
   "#.#.#.#.#o#.#",
   "#o.oo..o...o#",
   "#############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 6,
    "type": "balloon"
   },
   {
    "cx": 8,
    "cy": 3,
    "type": "armored"
   },
   {
    "cx": 9,
    "cy": 4,
    "type": "balloon"
   },
   {
    "cx": 10,
    "cy": 5,
    "type": "balloon"
   },
   {
    "cx": 11,
    "cy": 1,
    "type": "ghost"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "chaser"
   },
   {
    "cx": 7,
    "cy": 6,
    "type": "chaser"
   }
  ],
  "powerups": [
   {
    "cx": 9,
    "cy": 8,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 7,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 11,
    "cy": 4,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 6,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 7,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 9,
    "cy": 5,
    "kind": "curse",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 11,
   "cy": 9,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2498493551
 },
 {
  "id": "level_5_8",
  "mode": "campaign",
  "chapter": 5,
  "index": 8,
  "cols": 15,
  "rows": 13,
  "tiles": [
   "###############",
   "#......=...o..#",
   "#.#.#=#=#.#.#.#",
   "#.........o...#",
   "#.#o#o#.#.#=#.#",
   "#o...o.oo..=..#",
   "#.#.#.#.#o#.#.#",
   "#....o...o=...#",
   "#o#.#.#.#.#.#.#",
   "#...oo......o.#",
   "#o#.#=#o#.#.#.#",
   "#...o...o.o.==#",
   "###############"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 11,
    "cy": 2,
    "type": "armored"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "evader"
   },
   {
    "cx": 5,
    "cy": 8,
    "type": "chaser"
   },
   {
    "cx": 11,
    "cy": 8,
    "type": "evader"
   },
   {
    "cx": 9,
    "cy": 2,
    "type": "ghost"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "balloon"
   },
   {
    "cx": 4,
    "cy": 7,
    "type": "boss"
   }
  ],
  "powerups": [
   {
    "cx": 12,
    "cy": 11,
    "kind": "pierce",
    "hidden": true
   },
   {
    "cx": 12,
    "cy": 9,
    "kind": "shield",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 11,
    "kind": "remote",
    "hidden": true
   },
   {
    "cx": 8,
    "cy": 11,
    "kind": "curse",
    "hidden": true
   },
   {
    "cx": 10,
    "cy": 7,
    "kind": "curse",
    "hidden": true
   }
  ],
  "exit": {
   "cx": 13,
   "cy": 11,
   "hidden": true
  },
  "timeLimit": 230,
  "fire": 1,
  "bombs": 1,
  "seed": 2582381646
 }
];

export const PUZZLE_LEVELS = [
 {
  "id": "puzzle_01",
  "mode": "puzzle",
  "chapter": 0,
  "index": 1,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#......o..#",
   "#.#.#.#.#.#",
   "#...o.o.o.#",
   "#.#.#.#.#.#",
   "#.........#",
   "#.#o#.#o#.#",
   "#o.o......#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 2,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 1,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3394443113,
  "solution": {
   "bombs": 2,
   "cells": [
    "3,1",
    "3,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_02",
  "mode": "puzzle",
  "chapter": 0,
  "index": 2,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#..o..ooo.#",
   "#.#o#.#.#.#",
   "#.........#",
   "#.#o#.#.#.#",
   "#........o#",
   "#.#.#o#.#.#",
   "#.........#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3344424443,
  "solution": {
   "bombs": 2,
   "cells": [
    "5,3",
    "5,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_03",
  "mode": "puzzle",
  "chapter": 0,
  "index": 3,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#.........#",
   "#.#.#o#o#.#",
   "#......oo.#",
   "#o#.#.#.#.#",
   "#.........#",
   "#.#.#o#.#o#",
   "#....o....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3359631127,
  "solution": {
   "bombs": 2,
   "cells": [
    "3,3",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_04",
  "mode": "puzzle",
  "chapter": 0,
  "index": 4,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#........o#",
   "#.#.#.#.#.#",
   "#o........#",
   "#.#.#.#.#o#",
   "#.........#",
   "#.#.#o#o#o#",
   "#o..o.....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 8,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 5,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3444671241,
  "solution": {
   "bombs": 2,
   "cells": [
    "5,3",
    "7,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_05",
  "mode": "puzzle",
  "chapter": 0,
  "index": 5,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#...o.o...#",
   "#.#.#.#.#.#",
   "#.........#",
   "#.#o#.#.#.#",
   "#.......oo#",
   "#.#.#.#o#.#",
   "#...oo....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 5,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 2,
  "par": 1,
  "bombBudget": 2,
  "seed": 3459982654,
  "solution": {
   "bombs": 1,
   "cells": [
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_06",
  "mode": "puzzle",
  "chapter": 0,
  "index": 6,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#......o..#",
   "#.#o#.#.#.#",
   "#........o#",
   "#o#.#.#.#.#",
   "#.....o...#",
   "#.#.#.#.#o#",
   "#..o.o....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 1,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 2,
  "par": 1,
  "bombBudget": 2,
  "seed": 3410068713,
  "solution": {
   "bombs": 1,
   "cells": [
    "5,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_07",
  "mode": "puzzle",
  "chapter": 0,
  "index": 7,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#.........#",
   "#.#.#.#.#.#",
   "#o.o......#",
   "#o#o#o#o#.#",
   "#.o....o.o#",
   "#.#.#.#.#.#",
   "#......o..#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 2,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 4,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3437214503,
  "solution": {
   "bombs": 2,
   "cells": [
    "5,3",
    "7,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_08",
  "mode": "puzzle",
  "chapter": 0,
  "index": 8,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#....o....#",
   "#.#.#.#.#.#",
   "#...o.....#",
   "#.#.#.#.#o#",
   "#....oo..o#",
   "#o#.#.#.#.#",
   "#.o...o.o.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 7,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3511048614,
  "solution": {
   "bombs": 2,
   "cells": [
    "1,5",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_09",
  "mode": "puzzle",
  "chapter": 0,
  "index": 9,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#..o.o.o..#",
   "#.#o#.#.#.#",
   "#....o....#",
   "#.#.#.#.#.#",
   "#.....oo..#",
   "#.#.#.#.#.#",
   "#.o.o.o...#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 7,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3540288984,
  "solution": {
   "bombs": 2,
   "cells": [
    "1,5",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_10",
  "mode": "puzzle",
  "chapter": 0,
  "index": 10,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#...o....o#",
   "#.#.#.#.#.#",
   "#....o.o..#",
   "#.#.#.#o#.#",
   "#......o.o#",
   "#.#.#.#o#.#",
   "#.....oo..#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 6,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 2,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3480887070,
  "solution": {
   "bombs": 2,
   "cells": [
    "3,5",
    "4,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_11",
  "mode": "puzzle",
  "chapter": 0,
  "index": 11,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#..o..oo..#",
   "#.#.#.#o#.#",
   "#.........#",
   "#.#.#o#.#.#",
   "#......oo.#",
   "#.#.#.#o#o#",
   "#...o.....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 2,
    "type": "target"
   },
   {
    "cx": 4,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3460967581,
  "solution": {
   "bombs": 2,
   "cells": [
    "3,3",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_12",
  "mode": "puzzle",
  "chapter": 0,
  "index": 12,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#....oo...#",
   "#.#.#.#.#.#",
   "#...oo...o#",
   "#o#.#.#o#.#",
   "#o........#",
   "#o#.#.#.#o#",
   "#.........#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 5,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3535492837,
  "solution": {
   "bombs": 2,
   "cells": [
    "3,5",
    "5,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_13",
  "mode": "puzzle",
  "chapter": 0,
  "index": 13,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#........o#",
   "#.#.#.#o#.#",
   "#.oo...o..#",
   "#.#o#.#.#o#",
   "#......oo.#",
   "#.#.#.#.#o#",
   "#.o.....o.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 6,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 4,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 3493999174,
  "solution": {
   "bombs": 3,
   "cells": [
    "1,5",
    "3,5",
    "5,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_14",
  "mode": "puzzle",
  "chapter": 0,
  "index": 14,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#...o.o.oo#",
   "#.#.#.#.#.#",
   "#o........#",
   "#.#.#.#.#.#",
   "#o.o.oooo.#",
   "#.#.#.#.#.#",
   "#...o.....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 2,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 3410739453,
  "solution": {
   "bombs": 3,
   "cells": [
    "5,3",
    "7,3",
    "9,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_15",
  "mode": "puzzle",
  "chapter": 0,
  "index": 15,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#.....o...#",
   "#.#o#.#.#.#",
   "#.o.......#",
   "#.#o#.#o#.#",
   "#o..oo.o.o#",
   "#.#.#o#.#.#",
   "#.......o.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 3,
  "par": 2,
  "bombBudget": 3,
  "seed": 3394380750,
  "solution": {
   "bombs": 2,
   "cells": [
    "5,3",
    "7,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_16",
  "mode": "puzzle",
  "chapter": 0,
  "index": 16,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#....o....#",
   "#.#.#.#o#.#",
   "#o..o.o...#",
   "#.#.#.#.#.#",
   "#...o.....#",
   "#o#.#.#.#.#",
   "#o.o..ooo.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "target"
   },
   {
    "cx": 2,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 3445132523,
  "solution": {
   "bombs": 3,
   "cells": [
    "3,1",
    "3,3",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_17",
  "mode": "puzzle",
  "chapter": 0,
  "index": 17,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#...oo....#",
   "#.#.#.#.#.#",
   "#.o.....o.#",
   "#o#o#.#.#.#",
   "#o.oo.....#",
   "#.#.#o#.#.#",
   "#...o.o...#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 2,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 4,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 3430344755,
  "solution": {
   "bombs": 3,
   "cells": [
    "5,3",
    "7,3",
    "7,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_18",
  "mode": "puzzle",
  "chapter": 0,
  "index": 18,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#..o..o...#",
   "#.#o#o#.#.#",
   "#...o.o..o#",
   "#.#.#.#o#.#",
   "#....o....#",
   "#.#.#.#.#o#",
   "#......oo.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 3,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 3613432358,
  "solution": {
   "bombs": 3,
   "cells": [
    "3,5",
    "3,7",
    "5,7"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_19",
  "mode": "puzzle",
  "chapter": 0,
  "index": 19,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#..o......#",
   "#.#.#o#.#.#",
   "#.......oo#",
   "#o#.#.#o#.#",
   "#oo..o....#",
   "#o#.#.#o#o#",
   "#.o.....o.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 1,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 5,
  "par": 4,
  "bombBudget": 5,
  "seed": 3597283113,
  "solution": {
   "bombs": 4,
   "cells": [
    "7,1",
    "3,3",
    "5,3",
    "7,3"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_20",
  "mode": "puzzle",
  "chapter": 0,
  "index": 20,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#.....o...#",
   "#.#.#.#o#o#",
   "#......o.o#",
   "#o#.#.#.#o#",
   "#oo.......#",
   "#o#.#.#.#o#",
   "#.ooo.....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 6,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 4,
    "type": "target"
   },
   {
    "cx": 9,
    "cy": 5,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 5,
  "par": 4,
  "bombBudget": 5,
  "seed": 1566749929,
  "solution": {
   "bombs": 4,
   "cells": [
    "3,3",
    "3,5",
    "5,5",
    "7,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_21",
  "mode": "puzzle",
  "chapter": 0,
  "index": 21,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#.....o...#",
   "#.#.#.#.#o#",
   "#......o..#",
   "#o#.#.#.#o#",
   "#...o....o#",
   "#.#o#.#o#o#",
   "#o.ooo....#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 5,
    "cy": 2,
    "type": "target"
   },
   {
    "cx": 2,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 6,
    "type": "target"
   },
   {
    "cx": 7,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 5,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 1590020746,
  "solution": {
   "bombs": 3,
   "cells": [
    "3,3",
    "5,3",
    "5,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_22",
  "mode": "puzzle",
  "chapter": 0,
  "index": 22,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#....oo.o.#",
   "#.#.#.#o#.#",
   "#.......oo#",
   "#.#.#.#.#o#",
   "#......o..#",
   "#o#o#.#.#.#",
   "#..ooo..o.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 4,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 1,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 4,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 2,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 1597791671,
  "solution": {
   "bombs": 3,
   "cells": [
    "3,1",
    "3,3",
    "3,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_23",
  "mode": "puzzle",
  "chapter": 0,
  "index": 23,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#........o#",
   "#.#o#.#.#.#",
   "#o......o.#",
   "#.#o#.#o#.#",
   "#oo....o..#",
   "#.#.#.#.#o#",
   "#.o...ooo.#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 7,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 3,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 7,
    "type": "target"
   },
   {
    "cx": 4,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 4,
  "par": 3,
  "bombBudget": 4,
  "seed": 1619805740,
  "solution": {
   "bombs": 3,
   "cells": [
    "5,1",
    "5,3",
    "5,5"
   ],
   "first": 0
  }
 },
 {
  "id": "puzzle_24",
  "mode": "puzzle",
  "chapter": 0,
  "index": 24,
  "cols": 11,
  "rows": 9,
  "tiles": [
   "###########",
   "#...o.....#",
   "#.#.#.#.#o#",
   "#o.....o.o#",
   "#.#.#.#.#o#",
   "#.o.....o.#",
   "#.#o#.#o#.#",
   "#o..o.oo..#",
   "###########"
  ],
  "spawn": [
   1,
   1
  ],
  "enemies": [
   {
    "cx": 2,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 6,
    "cy": 3,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 5,
    "type": "target"
   },
   {
    "cx": 5,
    "cy": 1,
    "type": "target"
   },
   {
    "cx": 8,
    "cy": 1,
    "type": "target"
   }
  ],
  "powerups": [],
  "exit": null,
  "timeLimit": 120,
  "fire": 2,
  "bombs": 5,
  "par": 4,
  "bombBudget": 5,
  "seed": 1507494128,
  "solution": {
   "bombs": 4,
   "cells": [
    "5,1",
    "6,1",
    "3,3",
    "5,3"
   ],
   "first": 0
  }
 }
];

export function campaignLevelAt(index) {
  return CAMPAIGN_LEVELS[Math.max(0, Math.min(CAMPAIGN_LEVELS.length - 1, index))];
}

export function puzzleLevelAt(index) {
  return PUZZLE_LEVELS[Math.max(0, Math.min(PUZZLE_LEVELS.length - 1, index))];
}

export function levelById(id) {
  return CAMPAIGN_LEVELS.find((level) => level.id === id) ?? PUZZLE_LEVELS.find((level) => level.id === id) ?? null;
}
