// filepath: games/water-sort/tests/engine.test.mjs
import test from "node:test";
import assert from "node:assert/strict";
import { CAPACITY, COLORS, applyIntent, createState, dailySeed, difficultyFor, generateLevel, hashSeed, isValidSolution, isWon, legalMove, legalMoves, mulberry32, pour, replaySolution, solve } from "../js/engine.mjs";

test("开局使用紧凑试管数量，避免多余空管",()=>{assert.equal(difficultyFor(1).colors,2);assert.equal(difficultyFor(1).empties,1);assert.equal(generateLevel(1,1001).tubes.length,3);assert.equal(generateLevel(1,1001).tubes.filter((tube)=>tube.length===0).length,1);assert.equal(difficultyFor(2).colors,3);assert.equal(difficultyFor(3).colors,3);assert.equal(difficultyFor(4).colors,4);assert.equal(difficultyFor(6).colors,4);assert.equal(difficultyFor(7).colors,5);assert.equal(difficultyFor(11).colors,6);assert.equal(difficultyFor(41).colors,12);assert.equal(difficultyFor(4).empties,1);assert.equal(difficultyFor(7).empties,2);assert.equal(difficultyFor(3).tier,1);assert.equal(difficultyFor(10).tier,2);assert.equal(difficultyFor(20).tier,3);assert.equal(difficultyFor(35).tier,4);assert.equal(difficultyFor(50).tier,5);});
test("基础倒液规则：只允许同色顶或空管，并整段移动",()=>{const tubes=[["red","blue","blue"],["red"],[],[]];assert.equal(legalMove(tubes,0,1),false);assert.equal(legalMove(tubes,0,2),true);const moved=pour(tubes,0,2);assert.equal(moved.amount,2);assert.deepEqual(moved.tubes[0],["red"]);assert.deepEqual(moved.tubes[2],["blue","blue"]);});
test("胜利只接受纯色满管或空管",()=>{assert.equal(isWon([["red","red","red","red"],[],["blue","blue","blue","blue"]]),true);assert.equal(isWon([["red","blue"],[],[],[]]),false);});
test("低阶生成盘面可由 BFS 求解，且 par 来自实算",()=>{for(let level=1;level<=10;level++){const d=generateLevel(level,1000+level);assert.ok(d.par>0);assert.ok(solve(d.tubes,{maxNodes:70000}),`level ${level} should solve`);}});
test("第二关使用实际运行种子且有可执行解",()=>{const d=generateLevel(2,hashSeed("water-sort:2"));assert.equal(d.colors,3);assert.equal(d.empties,1);assert.ok(isValidSolution(d.tubes,d.solution));assert.ok(replaySolution(d.tubes,d.solution).every((tube)=>tube.length===0||tube.every((color)=>color===tube[0])));assert.deepEqual(replaySolution(d.tubes,d.solution).flat().sort(),["orange","orange","orange","orange","red","red","red","red","yellow","yellow","yellow","yellow"].sort());assert.ok(solve(d.tubes,{maxNodes:100000}),"level 2 must remain solvable");});
test("所有正式关卡都保留合法解路径",()=>{for(let level=1;level<=50;level++){const d=generateLevel(level,hashSeed(`water-sort:${level}`));assert.ok(isValidSolution(d.tubes,d.solution),`level ${level} solution must be executable and end in pure tubes`);}});
test("50 关都由反向构建携带可执行解路径",()=>{for(let level=1;level<=50;level++){const d=generateLevel(level,2000+level);let tubes=d.tubes.map((tube)=>[...tube]);for(const move of d.solution){const result=pour(tubes,move.from,move.to);assert.ok(result,`level ${level} move should be legal`);tubes=result.tubes;}assert.ok(isWon(tubes),`level ${level} should finish from construction proof`);assert.equal(d.par,d.solution.length);}});
test("键盘焦点移动不会伪造倾倒",()=>{let state=createState({tubes:[["red"],[],[],[]],level:1},{seed:1});let result=applyIntent(state,{type:"focus",index:2});assert.equal(result.event.type,"focus");assert.equal(result.state.focus,2);assert.equal(result.state.selected,null);result=applyIntent(result.state,{type:"select",index:0});assert.equal(result.event.type,"select");assert.equal(result.state.selected,0);result=applyIntent(result.state,{type:"focus",index:1});assert.equal(result.event.type,"focus");assert.equal(result.state.selected,0);assert.equal(result.state.moves,0);});
test("每日种子确定性",()=>{assert.equal(dailySeed("2026-09-14"),dailySeed("2026-09-14"));assert.notEqual(dailySeed("2026-09-14"),dailySeed("2026-09-15"));assert.deepEqual(generateLevel(35,dailySeed("2026-09-14")).tubes,generateLevel(35,dailySeed("2026-09-14")).tubes);});
test("合法操作总能执行，1000 步随机游走不破坏容量",()=>{const rng=mulberry32(42);let state=createState({level:6},{seed:42});state={...state,status:"playing",startedAt:1};for(let i=0;i<1000;i++){const moves=legalMoves(state.tubes);if(!moves.length||isWon(state.tubes))break;const move=moves[Math.floor(rng()*moves.length)];const result=applyIntent(state,{type:"select",index:move.from},{now:i+1});state=result.state;const result2=applyIntent(state,{type:"select",index:move.to},{now:i+1});state=result2.state;for(const t of state.tubes)assert.ok(t.length<=CAPACITY);}});
test("选中有液体试管后可以倒入空试管",()=>{let state=createState({tubes:[["red","blue"],[],["red"]],level:1},{seed:1});let result=applyIntent(state,{type:"select",index:0},{now:1});assert.equal(result.event.type,"select");result=applyIntent(result.state,{type:"select",index:1},{now:2});assert.equal(result.event.type,"pour");assert.deepEqual(result.state.tubes,[["red"],["blue"],["red"]]);assert.equal(result.state.moves,1);});
test("未选中来源时点击空试管仍然是无效起点",()=>{const state=createState({tubes:[["red"],[],[]],level:1},{seed:1});const result=applyIntent(state,{type:"select",index:1},{now:1});assert.equal(result.event.type,"invalid");assert.equal(result.state.toast,"empty-source");assert.equal(result.state.selected,null);});
test("终局状态不再接受倒液",()=>{let state=createState({tubes:[["red","red","red","red"],[],[],[]],level:1},{seed:1});state={...state,status:"won"};const result=applyIntent(state,{type:"select",index:0});assert.equal(result.event,null);assert.deepEqual(result.state.tubes,state.tubes);});

