// filepath: games/water-sort/js/storage.mjs
const KEY="doin.water-sort.v1";const MAX=800;
export function defaults(){return {sound:true,levels:{},daily:{date:null,bestScore:0,bestMoves:null}};}
function safeInt(v,min=0,max=MAX){const n=Math.round(Number(v));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):min;}
function backend(){try{if(typeof localStorage!=="undefined"){localStorage.setItem("__ws_probe__","1");localStorage.removeItem("__ws_probe__");return localStorage;}}catch{}const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v))};}
export function normalize(raw){const d=defaults();if(!raw||typeof raw!=="object"||Array.isArray(raw))return d;const out=defaults();if(typeof raw.sound==="boolean")out.sound=raw.sound;if(raw.levels&&typeof raw.levels==="object"&&!Array.isArray(raw.levels)){for(const [k,v] of Object.entries(raw.levels)){if(/^\d+$/.test(k))out.levels[k]={bestScore:safeInt(v?.bestScore),bestMoves:v?.bestMoves==null?null:safeInt(v.bestMoves,0,9999)};}}if(raw.daily&&typeof raw.daily==="object"&&/^\d{4}-\d{2}-\d{2}$/.test(raw.daily.date||""))out.daily={date:raw.daily.date,bestScore:safeInt(raw.daily.bestScore),bestMoves:raw.daily.bestMoves==null?null:safeInt(raw.daily.bestMoves,0,9999)};return out;}
export function load(){try{const raw=backend().getItem(KEY);return raw?normalize(JSON.parse(raw)):defaults();}catch{return defaults();}}
export function save(data){const out=normalize(data);try{backend().setItem(KEY,JSON.stringify(out));}catch{}return out;}
export function isLevelUnlocked(data,level,maxLevel=50){const n=Math.trunc(Number(level));if(!Number.isFinite(n)||n<1||n>maxLevel)return false;if(n===1)return true;const out=normalize(data);return Object.prototype.hasOwnProperty.call(out.levels,String(n-1));}
export function highestUnlocked(data,maxLevel=50){let level=1;while(level<maxLevel&&isLevelUnlocked(data,level+1,maxLevel))level++;return level;}
export function record(data,{level,score,moves,mode="level",date=null}){const out=normalize(data);const s=safeInt(score),m=safeInt(moves,0,9999);if(mode==="daily"){if(out.daily.date!==date)out.daily={date,bestScore:s,bestMoves:m};else{out.daily.bestScore=Math.max(out.daily.bestScore,s);out.daily.bestMoves=out.daily.bestMoves==null?m:Math.min(out.daily.bestMoves,m);}return {data:out,isNewBest:out.daily.bestScore===s&&out.daily.bestMoves===m};}const k=String(Math.max(1,Math.trunc(level)||1));const prev=out.levels[k]||{bestScore:0,bestMoves:null};const isNewBest=s>prev.bestScore;out.levels[k]={bestScore:Math.max(prev.bestScore,s),bestMoves:prev.bestMoves==null?m:Math.min(prev.bestMoves,m)};return {data:out,isNewBest};}
export function setSound(enabled){const d=load();d.sound=!!enabled;return save(d);}
